# NumPy Basics: Arrays and Vectorized Computation


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

- *array-based* operations for data cleaning, filtering, and transformation
- sorting, set operations
- linear algebra 
- need to use with pandas

### Arrays

In [ ]:
data = np.array([[1.5, -0.1,3], [0,-3,6.5]])
data


array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

NumPy can do 1D (a single list of numbers — like a vector), 
2D (a grid — like a spreadsheet), 
3D (a cube — like a stack of grids), and beyond. 
-> For your work, 1D arrays will be time-series signals (ECG), 2D arrays will be tables of vitals or grayscale images, and 3D/4D arrays will be color images or batches of images.
data.shape = (row, column)
dtype (data type). float64 is a number with a decimal point, stored using 64 bits of memory. It's NumPy's default for any array containing decimal numbers.

In [10]:
data * 10
data + data
data.shape
data.dtype

dtype('float64')

In [13]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [14]:
data2 = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
arr2=np.array(data2)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr2.ndim
arr2.shape
arr2.dtype

dtype('int64')

##### Other commands to make specific arrays

np.zeros
np.ones