# NumPy Basics: Arrays and Vectorized Computation


In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

- *array-based* operations for data cleaning, filtering, and transformation
- sorting, set operations
- linear algebra 
- need to use with pandas

### Arrays

In [4]:
data = np.array([[1.5, -0.1,3], [0,-3,6.5]])
data


array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

NumPy can do 1D (a single list of numbers — like a vector), 
2D (a grid — like a spreadsheet), 
3D (a cube — like a stack of grids), and beyond. 
-> For your work, 1D arrays will be time-series signals (ECG), 2D arrays will be tables of vitals or grayscale images, and 3D/4D arrays will be color images or batches of images.
data.shape = (row, column)
dtype (data type). float64 is a number with a decimal point, stored using 64 bits of memory. It's NumPy's default for any array containing decimal numbers.

In [5]:
data * 10
data + data
data.shape
data.dtype

dtype('float64')

In [6]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [7]:
data2 = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
arr2=np.array(data2)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
arr2.ndim
arr2.shape
arr2.dtype

dtype('int64')

- np allows operations like matrices through vectorization
- between same size yield Boolean arrays 
- array indexing = selecting parts of data

In [9]:
arr = np.arange(10)
arr
arr[5]
arr[5:8]
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [ ]:
arr_slice = arr[5:8]
arr_slice
arr_slice[1]=12345
arr[5:8].copy()
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [11]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d [2]
arr2d [0] [2]

np.int64(3)

In [17]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]
old_values = arr3d[0].copy()
arr3d[0]=42
arr3d[0]=old_values
arr3d[1,0]
x = arr3d[1]
x
x[0]

array([7, 8, 9])

In [20]:
arr
arr[1:6]

array([ 1,  2,  3,  4, 12])

**start of an array is inclusive but end is exclusive**

**axis 0 = rows that go down
axis 1 = columns that go right**

In [22]:
arr2d
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
lower_dim_slice = arr2d[1, :2]
lower_dim_slice

array([4, 5])

In [25]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])
names
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [31]:
names == 'Bob'
data[names == "Bob"]
data[names == "Bob", 1:]
data[names == "Bob", 0]
names !="Bob"
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [35]:
cond = names == "Bob"
data[~cond]
mask = (names == "Bob") | (names == "Will")
mask
data [mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

mask is a boolean array to change parts of the array (ex. bob/will)
- it's like a stencil that only selects the "true" parts of the array

In [37]:
data[data < 0] = 0
data[names != "Joe"] = 7
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

In [41]:
arr = np.zeros((8, 4))
for i in range(8):
    arr [i] = i
arr[[4, 3, 0, 6]]
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [45]:
arr = np.arange(32).reshape((8, 4))
arr
arr[[1, 5, 7, 2], [0, 3, 1, 2]]
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [ ]:
fancy indexing always copies data into a new array unlike normal slicing

In [ ]:
arr = np.arange(15).reshape((3, 5))
arr
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [49]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
arr
np.dot(arr.T, arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])